// Minimal ISO 3166-1 alpha-2 → continent map. Covers GeoGuessr-relevant countries.
// Falls back to rough lat/lng bounds when country_code is missing.

const ISO_TO_CONTINENT: Record<string, string> = {
  // Europe
  al: "Europe",
  ad: "Europe",
  at: "Europe",
  by: "Europe",
  be: "Europe",
  ba: "Europe",
  bg: "Europe",
  hr: "Europe",
  cy: "Europe",
  cz: "Europe",
  dk: "Europe",
  ee: "Europe",
  fo: "Europe",
  fi: "Europe",
  fr: "Europe",
  de: "Europe",
  gi: "Europe",
  gr: "Europe",
  gg: "Europe",
  hu: "Europe",
  is: "Europe",
  ie: "Europe",
  im: "Europe",
  it: "Europe",
  je: "Europe",
  xk: "Europe",
  lv: "Europe",
  li: "Europe",
  lt: "Europe",
  lu: "Europe",
  mt: "Europe",
  md: "Europe",
  mc: "Europe",
  me: "Europe",
  nl: "Europe",
  mk: "Europe",
  no: "Europe",
  pl: "Europe",
  pt: "Europe",
  ro: "Europe",
  sm: "Europe",
  rs: "Europe",
  sk: "Europe",
  si: "Europe",
  es: "Europe",
  se: "Europe",
  ch: "Europe",
  ua: "Europe",
  gb: "Europe",
  va: "Europe",
  ru: "Europe",

  // Asia
  af: "Asia",
  am: "Asia",
  az: "Asia",
  bh: "Asia",
  bd: "Asia",
  bt: "Asia",
  bn: "Asia",
  kh: "Asia",
  cn: "Asia",
  ge: "Asia",
  hk: "Asia",
  in: "Asia",
  id: "Asia",
  ir: "Asia",
  iq: "Asia",
  il: "Asia",
  jp: "Asia",
  jo: "Asia",
  kz: "Asia",
  kp: "Asia",
  kr: "Asia",
  kw: "Asia",
  kg: "Asia",
  la: "Asia",
  lb: "Asia",
  mo: "Asia",
  my: "Asia",
  mv: "Asia",
  mn: "Asia",
  mm: "Asia",
  np: "Asia",
  om: "Asia",
  pk: "Asia",
  ph: "Asia",
  qa: "Asia",
  sa: "Asia",
  sg: "Asia",
  lk: "Asia",
  sy: "Asia",
  tw: "Asia",
  tj: "Asia",
  th: "Asia",
  tl: "Asia",
  tr: "Asia",
  tm: "Asia",
  ae: "Asia",
  uz: "Asia",
  vn: "Asia",
  ye: "Asia",
  ps: "Asia",

  // Africa
  dz: "Africa",
  ao: "Africa",
  bj: "Africa",
  bw: "Africa",
  bf: "Africa",
  bi: "Africa",
  cm: "Africa",
  cv: "Africa",
  cf: "Africa",
  td: "Africa",
  km: "Africa",
  cd: "Africa",
  cg: "Africa",
  ci: "Africa",
  dj: "Africa",
  eg: "Africa",
  gq: "Africa",
  er: "Africa",
  sz: "Africa",
  et: "Africa",
  ga: "Africa",
  gm: "Africa",
  gh: "Africa",
  gn: "Africa",
  gw: "Africa",
  ke: "Africa",
  ls: "Africa",
  lr: "Africa",
  ly: "Africa",
  mg: "Africa",
  mw: "Africa",
  ml: "Africa",
  mr: "Africa",
  mu: "Africa",
  ma: "Africa",
  mz: "Africa",
  na: "Africa",
  ne: "Africa",
  ng: "Africa",
  rw: "Africa",
  st: "Africa",
  sn: "Africa",
  sc: "Africa",
  sl: "Africa",
  so: "Africa",
  za: "Africa",
  ss: "Africa",
  sd: "Africa",
  tz: "Africa",
  tg: "Africa",
  tn: "Africa",
  ug: "Africa",
  eh: "Africa",
  zm: "Africa",
  zw: "Africa",

  // North America
  ai: "North America",
  ag: "North America",
  aw: "North America",
  bs: "North America",
  bb: "North America",
  bz: "North America",
  bm: "North America",
  vg: "North America",
  ca: "North America",
  ky: "North America",
  cr: "North America",
  cu: "North America",
  cw: "North America",
  dm: "North America",
  do: "North America",
  sv: "North America",
  gl: "North America",
  gd: "North America",
  gp: "North America",
  gt: "North America",
  ht: "North America",
  hn: "North America",
  jm: "North America",
  mq: "North America",
  mx: "North America",
  ms: "North America",
  ni: "North America",
  pa: "North America",
  pr: "North America",
  kn: "North America",
  lc: "North America",
  pm: "North America",
  vc: "North America",
  sx: "North America",
  tt: "North America",
  tc: "North America",
  us: "North America",
  vi: "North America",

  // South America
  ar: "South America",
  bo: "South America",
  br: "South America",
  cl: "South America",
  co: "South America",
  ec: "South America",
  fk: "South America",
  gf: "South America",
  gy: "South America",
  py: "South America",
  pe: "South America",
  sr: "South America",
  uy: "South America",
  ve: "South America",

  // Oceania
  as: "Oceania",
  au: "Oceania",
  ck: "Oceania",
  fj: "Oceania",
  pf: "Oceania",
  gu: "Oceania",
  ki: "Oceania",
  mh: "Oceania",
  fm: "Oceania",
  nr: "Oceania",
  nc: "Oceania",
  nz: "Oceania",
  nu: "Oceania",
  mp: "Oceania",
  pw: "Oceania",
  pg: "Oceania",
  pn: "Oceania",
  ws: "Oceania",
  sb: "Oceania",
  tk: "Oceania",
  to: "Oceania",
  tv: "Oceania",
  vu: "Oceania",
  wf: "Oceania",

  // Antarctica
  aq: "Antarctica",
}

export function continentFrom(
  countryCode?: string,
  lat?: number,
  lng?: number
): string | undefined {
  if (countryCode) {
    const found = ISO_TO_CONTINENT[countryCode.toLowerCase()]
    if (found) return found
  }
  if (lat !== undefined && lng !== undefined) {
    return continentFromCoords(lat, lng)
  }
  return undefined
}

function continentFromCoords(lat: number, lng: number): string {
  if (lat < -60) return "Antarctica"
  if (lat < -10 && lng > 110) return "Oceania"
  if (lat < 15 && lng > -82 && lng < -34) return "South America"
  if (lat > 5 && lng > -170 && lng < -50) return "North America"
  if (lat > 36 && lng > -31 && lng < 60) return "Europe"
  if (lat > -35 && lat < 37 && lng > -18 && lng < 52) return "Africa"
  return "Asia"
}
